### ISSUE TITLE
Failed to resolve import "element-plus/lib/theme-chalk/el-input-number.css" when upgrade element-plus to 1.2.0

### ISSUE THREAD

**Issue by natuan62** [newbee-ltd/vue3-admin#19]
- Error when run `yarn dev`

```
10:16:57 AM [vite] Internal server error: Failed to resolve import "element-plus/lib/theme-chalk/el-input-number.css" from "src/main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/Desktop/vue3-admin/src/main.js
  1  |  import "element-plus/lib/theme-chalk/el-input-number.css";
     |          ^
  2  |  import "element-plus/lib/theme-chalk/el-checkbox.css";
  3  |  import "element-plus/lib/theme-chalk/el-cascader.css";
      at formatError (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
      at TransformContext.error (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
      at normalizeUrl (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
      at async TransformContext.transform (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
      at async Object.transform (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/Users/anhtuannguyen/Desktop/vue3-admin/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29) (x2)
```

- Packages.json after upgrade

```
{
  "dependencies": {
    "axios": "^0.24.0",
    "element-plus": "^1.2.0-beta.3",
    "js-md5": "^0.7.3",
    "vue": "^3.2.22",
    "vue-router": "^4.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/runtime": "^7.16.3",
    "@rollup/plugin-babel": "^5.3.0",
    "@vitejs/plugin-vue": "^1.9.4",
    "@vue/compiler-sfc": "^3.2.22",
    "babel": "^6.23.0",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-import": "^1.13.3",
    "element-theme-chalk": "^2.15.6",
    "vite": "^2.6.14",
    "vite-babel-plugin": "^0.0.2",
    "vite-plugin-babel-import": "^2.0.5",
    "vite-plugin-imp": "^2.0.10"
  }
}

```

- Packages.json changed

![Screen Shot 2021-11-19 at 10 24 16](https://user-images.githubusercontent.com/10808157/142559784-25becd42-a846-4fc5-9634-ca8088a28119.png)

**Comment by Nick930826** [comment]
使用Vite构建项目的时候，看看vite.config.js里配置的按需插件，在编译后，能否正确获取到样式路径。
